require 'benchmark'

module Version1

  class MedianFinder

  	def initialize
      @large = PQueue.new { |a,b| a < b } # MinHeap
      @small = PQueue.new { |a,b| a > b } # MaxHeap
    end
   
    def add_num(num)
      @large << num    
      @small << @large.pop

      # make sure the the size diff btw @large and @small is no greater than 1
      if @small.size > @large.size
        @large << @small.pop
      end
      # puts "@large = #{@large.inspect} @small = #{@small.inspect}"
    end

    def find_median()
      if @large.size == @small.size
        (@large.top + @small.top)*1.0/2
      else
        @large.top
      end
    end
  end

  class PQueue

    attr_reader :que, :cmp

    def initialize(&block)
      @que = [nil]
      @size = 0
      @cmp = block
    end

    def size
      @size
    end

    def <<(v)
      @size += 1
      @que[@size] = v
    
      i = @size
      while !@que[i].nil?
        heapify(@que, i)
        i /= 2
      end

      self
    end

    def pop
      return nil if empty?
      
      ans = @que[1]

      # @que has at least two element (e.g. [nil, 1], [nil, 3,2,1])
      swap(@que, 1, @size)
      @que[@size] = nil
      @size -= 1
      heapify(@que, 1)

      ans
    end

    def top
      empty? ? nil : @que[1]
    end

    def empty?
      size == 0
    end

    def inspect
      "<pq: size=#{size}, top=#{top || "nil"}>"
    end

    private

    def heapify(queue, i)
      
      max_i, left_i, right_i = i, i*2, i*2+1

      if !queue[left_i].nil? and !@cmp.call(queue[max_i], queue[left_i])
        max_i = left_i
      end

      if !queue[right_i].nil? and !@cmp.call(queue[max_i], queue[right_i])
        max_i = right_i
      end

      if max_i != i
        swap(queue, i, max_i)
        heapify(queue, max_i)
      end

    end

    def swap(arr, i1, i2)
      arr[i1], arr[i2] = arr[i2], arr[i1]
    end

  end

  def self.run 

    mf = MedianFinder.new

    mf.add_num(1768)
    mf.find_median()
    mf.add_num(3181)
    mf.find_median()
    mf.add_num(2366)
    mf.find_median()
    mf.add_num(3696)
    mf.find_median()
    mf.add_num(13344)
    mf.find_median()
    mf.add_num(4168)
    mf.find_median()
    mf.add_num(7751)
    mf.find_median()
    mf.add_num(13282)
    mf.find_median()
    mf.add_num(8475)
    mf.find_median()
    mf.add_num(13661)
    mf.find_median()
    mf.add_num(7766)
    mf.find_median()
    mf.add_num(8742)
    mf.find_median()
    mf.add_num(17861)
    mf.find_median()
    mf.add_num(13474)
    mf.find_median()
    mf.add_num(7076)
    mf.find_median()
    mf.add_num(16490)
    mf.find_median()
    mf.add_num(11533)
    mf.find_median()
    mf.add_num(7631)
    mf.find_median()
    mf.add_num(2588)
    mf.find_median()
    mf.add_num(14807)
    mf.find_median()
    mf.add_num(9550)
    mf.find_median()
    mf.add_num(19927)
    mf.find_median()
    mf.add_num(16810)
    mf.find_median()
    mf.add_num(9120)
    mf.find_median()
    mf.add_num(2887)
    mf.find_median()
    mf.add_num(18040)
    mf.find_median()
    mf.add_num(20397)
    mf.find_median()
    mf.add_num(19039)
    mf.find_median()
    mf.add_num(10943)
    mf.find_median()
    mf.add_num(10968)
    mf.find_median()
    mf.add_num(14156)
    mf.find_median()
    mf.add_num(18520)
    mf.find_median()
    mf.add_num(13696)
    mf.find_median()
    mf.add_num(17362)
    mf.find_median()
    mf.add_num(2139)
    mf.find_median()
    mf.add_num(6677)
    mf.find_median()
    mf.add_num(13465)
    mf.find_median()
    mf.add_num(16505)
    mf.find_median()
    mf.add_num(3832)
    mf.find_median()
    mf.add_num(18544)
    mf.find_median()
    mf.add_num(5959)
    mf.find_median()
    mf.add_num(15309)
    mf.find_median()
    mf.add_num(19828)
    mf.find_median()
    mf.add_num(10831)
    mf.find_median()
    mf.add_num(1174)
    mf.find_median()
    mf.add_num(461)
    mf.find_median()
    mf.add_num(10460)
    mf.find_median()
    mf.add_num(18685)
    mf.find_median()
    mf.add_num(20384)
    mf.find_median()
    mf.add_num(16380)
    mf.find_median()
    mf.add_num(11059)
    mf.find_median()
    mf.add_num(2973)
    mf.find_median()
    mf.add_num(11622)
    mf.find_median()
    mf.add_num(8451)
    mf.find_median()
    mf.add_num(16506)
    mf.find_median()
    mf.add_num(188)
    mf.find_median()
    mf.add_num(906)
    mf.find_median()
    mf.add_num(20330)
    mf.find_median()
    mf.add_num(17712)
    mf.find_median()
    mf.add_num(10009)
    mf.find_median()
    mf.add_num(19454)
    mf.find_median()
    mf.add_num(2528)
    mf.find_median()
    mf.add_num(1952)
    mf.find_median()
    mf.add_num(6381)
    mf.find_median()
    mf.add_num(19434)
    mf.find_median()
    mf.add_num(19797)
    mf.find_median()
    mf.add_num(9200)
    mf.find_median()
    mf.add_num(15402)
    mf.find_median()
    mf.add_num(14809)
    mf.find_median()
    mf.add_num(9823)
    mf.find_median()
    mf.add_num(24)
    mf.find_median()
    mf.add_num(7779)
    mf.find_median()
    mf.add_num(6114)
    mf.find_median()
    mf.add_num(4501)
    mf.find_median()
    mf.add_num(17045)
    mf.find_median()
    mf.add_num(11499)
    mf.find_median()
    mf.add_num(12422)
    mf.find_median()
    mf.add_num(277)
    mf.find_median()
    mf.add_num(10142)
    mf.find_median()
    mf.add_num(1754)
    mf.find_median()
    mf.add_num(2621)
    mf.find_median()
    mf.add_num(18990)
    mf.find_median()
    mf.add_num(8577)
    mf.find_median()
    mf.add_num(494)
    mf.find_median()
    mf.add_num(19789)
    mf.find_median()
    mf.add_num(18265)
    mf.find_median()
    mf.add_num(18405)
    mf.find_median()
    mf.add_num(7117)
    mf.find_median()
    mf.add_num(14556)
    mf.find_median()
    mf.add_num(6305)
    mf.find_median()
    mf.add_num(9286)
    mf.find_median()
    mf.add_num(5649)
    mf.find_median()
    mf.add_num(11793)
    mf.find_median()
    mf.add_num(14560)
    mf.find_median()
    mf.add_num(8769)
    mf.find_median()
    mf.add_num(12791)
    mf.find_median()
    mf.add_num(3681)
    mf.find_median()
    mf.add_num(6702)
    mf.find_median()
    mf.add_num(17822)
    mf.find_median()
    mf.add_num(14166)
    mf.find_median()
    mf.add_num(8526)
    mf.find_median()
    mf.add_num(4705)
    mf.find_median()
    mf.add_num(9890)
    mf.find_median()
    mf.add_num(2105)
    mf.find_median()
    mf.add_num(15525)
    mf.find_median()
    mf.add_num(10274)
    mf.find_median()
    mf.add_num(8849)
    mf.find_median()
    mf.add_num(12567)
    mf.find_median()
    mf.add_num(14056)
    mf.find_median()
    mf.add_num(8169)
    mf.find_median()
    mf.add_num(14960)
    mf.find_median()
    mf.add_num(13839)
    mf.find_median()
    mf.add_num(17929)
    mf.find_median()
    mf.add_num(10847)
    mf.find_median()
    mf.add_num(5978)
    mf.find_median()
    mf.add_num(18971)
    mf.find_median()
    mf.add_num(10026)
    mf.find_median()
    mf.add_num(4077)
    mf.find_median()
    mf.add_num(17800)
    mf.find_median()
    mf.add_num(10839)
    mf.find_median()
    mf.add_num(4663)
    mf.find_median()
    mf.add_num(20352)
    mf.find_median()
    mf.add_num(786)
    mf.find_median()
    mf.add_num(15528)
    mf.find_median()
    mf.add_num(11840)
    mf.find_median()
    mf.add_num(15742)
    mf.find_median()
    mf.add_num(382)
    mf.find_median()
    mf.add_num(10234)
    mf.find_median()
    mf.add_num(9663)
    mf.find_median()
    mf.add_num(9045)
    mf.find_median()
    mf.add_num(16650)
    mf.find_median()
    mf.add_num(189)
    mf.find_median()
    mf.add_num(10051)
    mf.find_median()
    mf.add_num(13887)
    mf.find_median()
    mf.add_num(14600)
    mf.find_median()
    mf.add_num(18357)
    mf.find_median()
    mf.add_num(4629)
    mf.find_median()
    mf.add_num(5923)
    mf.find_median()
    mf.add_num(102)
    mf.find_median()
    mf.add_num(16934)
    mf.find_median()
    mf.add_num(11941)
    mf.find_median()
    mf.add_num(4869)
    mf.find_median()
    mf.add_num(20066)
    mf.find_median()
    mf.add_num(708)
    mf.find_median()
    mf.add_num(4104)
    mf.find_median()
    mf.add_num(682)
    mf.find_median()
    mf.add_num(8242)
    mf.find_median()
    mf.add_num(18889)
    mf.find_median()
    mf.add_num(7726)
    mf.find_median()
    mf.add_num(16342)
    mf.find_median()
    mf.add_num(1184)
    mf.find_median()
    mf.add_num(16599)
    mf.find_median()
    mf.add_num(6129)
    mf.find_median()
    mf.add_num(839)
    mf.find_median()
    mf.add_num(7179)
    mf.find_median()
    mf.add_num(13523)
    mf.find_median()
    mf.add_num(6333)
    mf.find_median()
    mf.add_num(6333)
    mf.find_median()
    mf.add_num(8176)
    mf.find_median()
    mf.add_num(7605)
    mf.find_median()
    mf.add_num(219)
    mf.find_median()
    mf.add_num(14372)
    mf.find_median()
    mf.add_num(5557)
    mf.find_median()
    mf.add_num(12689)
    mf.find_median()
    mf.add_num(10839)
    mf.find_median()
    mf.add_num(1550)
    mf.find_median()
    mf.add_num(18342)
    mf.find_median()
    mf.add_num(16379)
    mf.find_median()
    mf.add_num(13003)
    mf.find_median()
    mf.add_num(5824)
    mf.find_median()
    mf.add_num(16187)
    mf.find_median()
    mf.add_num(685)
    mf.find_median()
    mf.add_num(11109)
    mf.find_median()
    mf.add_num(20345)
    mf.find_median()
    mf.add_num(7322)
    mf.find_median()
    mf.add_num(17437)
    mf.find_median()
    mf.add_num(11362)
    mf.find_median()
    mf.add_num(11348)
    mf.find_median()
    mf.add_num(9064)
    mf.find_median()
    mf.add_num(4978)
    mf.find_median()
    mf.add_num(5490)
    mf.find_median()
    mf.add_num(404)
    mf.find_median()
    mf.add_num(17862)
    mf.find_median()
    mf.add_num(7997)
    mf.find_median()
    mf.add_num(16300)
    mf.find_median()
    mf.add_num(6447)
    mf.find_median()
    mf.add_num(14819)
    mf.find_median()
    mf.add_num(2648)
    mf.find_median()
    mf.add_num(11108)
    mf.find_median()
    mf.add_num(18522)
    mf.find_median()
    mf.add_num(10501)
    mf.find_median()
    mf.add_num(11689)
    mf.find_median()
    mf.add_num(12426)
    mf.find_median()
    mf.add_num(4122)
    mf.find_median()
    mf.add_num(6393)
    mf.find_median()
    mf.add_num(18208)
    mf.find_median()
    mf.add_num(19882)
    mf.find_median()
    mf.add_num(9438)
    mf.find_median()
    mf.add_num(7176)
    mf.find_median()
    mf.add_num(19867)
    mf.find_median()
    mf.add_num(5008)
    mf.find_median()
    mf.add_num(7377)
    mf.find_median()
    mf.add_num(193)
    mf.find_median()
    mf.add_num(10418)
    mf.find_median()
    mf.add_num(19021)
    mf.find_median()
    mf.add_num(16368)
    mf.find_median()
    mf.add_num(9135)
    mf.find_median()
    mf.add_num(19201)
    mf.find_median()
    mf.add_num(17383)
    mf.find_median()
    mf.add_num(5967)
    mf.find_median()
    mf.add_num(14254)
    mf.find_median()
    mf.add_num(3846)
    mf.find_median()
    mf.add_num(12680)
    mf.find_median()
    mf.add_num(9908)
    mf.find_median()
    mf.add_num(4089)
    mf.find_median()
    mf.add_num(8658)
    mf.find_median()
    mf.add_num(9076)
    mf.find_median()
    mf.add_num(9478)
    mf.find_median()
    mf.add_num(8263)
    mf.find_median()
    mf.add_num(4512)
    mf.find_median()
    mf.add_num(14221)
    mf.find_median()
    mf.add_num(6296)
    mf.find_median()
    mf.add_num(2444)
    mf.find_median()
    mf.add_num(11765)
    mf.find_median()
    mf.add_num(8587)
    mf.find_median()
    mf.add_num(3066)
    mf.find_median()
    mf.add_num(5716)
    mf.find_median()
    mf.add_num(18840)
    mf.find_median()
    mf.add_num(9965)
    mf.find_median()
    mf.add_num(12035)
    mf.find_median()
    mf.add_num(8946)
    mf.find_median()
    mf.add_num(12118)
    mf.find_median()
    mf.add_num(11603)
    mf.find_median()
    mf.add_num(5458)
    mf.find_median()
    mf.add_num(9077)
    mf.find_median()
    mf.add_num(19132)
    mf.find_median()
    mf.add_num(8213)
    mf.find_median()
    mf.add_num(4324)
    mf.find_median()
    mf.add_num(1228)
    mf.find_median()
    mf.add_num(17439)
    mf.find_median()
    mf.add_num(18123)
    mf.find_median()
    mf.add_num(6459)
    mf.find_median()
    mf.add_num(15910)
    mf.find_median()
    mf.add_num(10669)
    mf.find_median()
    mf.add_num(1086)
    mf.find_median()
    mf.add_num(9400)
    mf.find_median()
    mf.add_num(18870)
    mf.find_median()
    mf.add_num(9929)
    mf.find_median()
    mf.add_num(9990)
    mf.find_median()
    mf.add_num(17760)
    mf.find_median()
    mf.add_num(5868)
    mf.find_median()
    mf.add_num(13765)
    mf.find_median()
    mf.add_num(2462)
    mf.find_median()
    mf.add_num(6446)
    mf.find_median()
    mf.add_num(19590)
    mf.find_median()
    mf.add_num(8938)
    mf.find_median()
    mf.add_num(11355)
    mf.find_median()
    mf.add_num(10679)
    mf.find_median()
    mf.add_num(4818)
    mf.find_median()
    mf.add_num(16978)
    mf.find_median()
    mf.add_num(243)
    mf.find_median()
    mf.add_num(11693)
    mf.find_median()
    mf.add_num(10295)
    mf.find_median()
    mf.add_num(13403)
    mf.find_median()
    mf.add_num(5126)
    mf.find_median()
    mf.add_num(4772)
    mf.find_median()
    mf.add_num(5351)
    mf.find_median()
    mf.add_num(789)
    mf.find_median()
    mf.add_num(19759)
    mf.find_median()
    mf.add_num(5342)
    mf.find_median()
    mf.add_num(10674)
    mf.find_median()
    mf.add_num(17287)
    mf.find_median()
    mf.add_num(20180)
    mf.find_median()
    mf.add_num(14940)
    mf.find_median()
    mf.add_num(18630)
    mf.find_median()
    mf.add_num(14467)
    mf.find_median()
    mf.add_num(18404)
    mf.find_median()
    mf.add_num(18556)
    mf.find_median()
    mf.add_num(11644)
    mf.find_median()
    mf.add_num(2946)
    mf.find_median()
    mf.add_num(7620)
    mf.find_median()
    mf.add_num(19467)
    mf.find_median()
    mf.add_num(18391)
    mf.find_median()
    mf.add_num(16486)
    mf.find_median()
    mf.add_num(16291)
    mf.find_median()
    mf.add_num(1096)
    mf.find_median()
    mf.add_num(12200)
    mf.find_median()
    mf.add_num(5641)
    mf.find_median()
    mf.add_num(13434)
    mf.find_median()
    mf.add_num(9436)
    mf.find_median()
    mf.add_num(14408)
    mf.find_median()
    mf.add_num(10710)
    mf.find_median()
    mf.add_num(5120)
    mf.find_median()
    mf.add_num(5954)
    mf.find_median()
    mf.add_num(16400)
    mf.find_median()
    mf.add_num(11221)
    mf.find_median()
    mf.add_num(4706)
    mf.find_median()
    mf.add_num(15090)
    mf.find_median()
    mf.add_num(4940)
    mf.find_median()
    mf.add_num(16426)
    mf.find_median()
    mf.add_num(16991)
    mf.find_median()
    mf.add_num(9972)
    mf.find_median()
    mf.add_num(19559)
    mf.find_median()
    mf.add_num(9092)
    mf.find_median()
    mf.add_num(12857)
    mf.find_median()
    mf.add_num(15527)
    mf.find_median()
    mf.add_num(11514)
    mf.find_median()
    mf.add_num(19781)
    mf.find_median()
    mf.add_num(17590)
    mf.find_median()
    mf.add_num(6694)
    mf.find_median()
    mf.add_num(6736)
    mf.find_median()
    mf.add_num(5624)
    mf.find_median()
    mf.add_num(10589)
    mf.find_median()
    mf.add_num(20320)
    mf.find_median()
    mf.add_num(6487)
    mf.find_median()
    mf.add_num(19074)
    mf.find_median()
    mf.add_num(10132)
    mf.find_median()
    mf.add_num(20427)
    mf.find_median()
    mf.add_num(465)
    mf.find_median()
    mf.add_num(11186)
    mf.find_median()
    mf.add_num(19120)
    mf.find_median()
    mf.add_num(5081)
    mf.find_median()
    mf.add_num(6648)
    mf.find_median()
    mf.add_num(9294)
    mf.find_median()
    mf.add_num(14751)
    mf.find_median()
    mf.add_num(13117)
    mf.find_median()
    mf.add_num(8846)
    mf.find_median()
    mf.add_num(18994)
    mf.find_median()
    mf.add_num(17383)
    mf.find_median()
    mf.add_num(9983)
    mf.find_median()
    mf.add_num(696)
    mf.find_median()
    mf.add_num(1730)
    mf.find_median()
    mf.add_num(19670)
    mf.find_median()
    mf.add_num(17930)
    mf.find_median()
    mf.add_num(17244)
    mf.find_median()
    mf.add_num(13957)
    mf.find_median()
    mf.add_num(2002)
    mf.find_median()
    mf.add_num(3160)
    mf.find_median()
    mf.add_num(4001)
    mf.find_median()
    mf.add_num(2012)
    mf.find_median()
    mf.add_num(6664)
    mf.find_median()
    mf.add_num(2574)
    mf.find_median()
    mf.add_num(14480)
    mf.find_median()
    mf.add_num(13773)
    mf.find_median()
    mf.add_num(11745)
    mf.find_median()
    mf.add_num(14477)
    mf.find_median()
    mf.add_num(6537)
    mf.find_median()
    mf.add_num(15390)
    mf.find_median()
    mf.add_num(17494)
    mf.find_median()
    mf.add_num(13766)
    mf.find_median()
    mf.add_num(13141)
    mf.find_median()
    mf.add_num(20013)
    mf.find_median()
    mf.add_num(8059)
    mf.find_median()
    mf.add_num(3207)
    mf.find_median()
    mf.add_num(17012)
    mf.find_median()
    mf.add_num(6631)
    mf.find_median()
    mf.add_num(4004)
    mf.find_median()
    mf.add_num(12523)
    mf.find_median()
    mf.add_num(20130)
    mf.find_median()
    mf.add_num(5202)
    mf.find_median()
    mf.add_num(4307)
    mf.find_median()
    mf.add_num(10746)
    mf.find_median()
    mf.add_num(4028)
    mf.find_median()
    mf.add_num(16231)
    mf.find_median()
    mf.add_num(11236)
    mf.find_median()
    mf.add_num(13017)
    mf.find_median()
    mf.add_num(15323)
    mf.find_median()
    mf.add_num(7958)
    mf.find_median()
    mf.add_num(9042)
    mf.find_median()
    mf.add_num(6907)
    mf.find_median()
    mf.add_num(6011)
    mf.find_median()
    mf.add_num(97)
    mf.find_median()
    mf.add_num(4403)
    mf.find_median()
    mf.add_num(17352)
    mf.find_median()
    mf.add_num(18833)
    mf.find_median()
    mf.add_num(63)
    mf.find_median()
    mf.add_num(7214)
    mf.find_median()
    mf.add_num(17582)
    mf.find_median()
  end
end

module Version2
  class MedianFinder

    def initialize
      @large = PQueue.new { |a,b| a < b } # MinHeap
      @small = PQueue.new { |a,b| a > b } # MaxHeap
    end
   
    def add_num(num)
      @large << num    
      @small << @large.pop

      # make sure the the size diff btw @large and @small is no greater than 1
      if @small.size > @large.size
        @large << @small.pop
      end
      # puts "@large = #{@large.inspect} @small = #{@small.inspect}"
    end

    def find_median()
      if @large.size == @small.size
        (@large.top + @small.top)*1.0/2
      else
        @large.top
      end
    end
  end

  class PQueue

    attr_reader :que, :cmp

    def initialize(&block)
      @que = [nil]
      @cmp = block
    end

    def size
      @que.size - 1
    end

    def <<(v)
      @que << v
    
      i = @que.size-1
      while !@que[i].nil?
        heapify(@que, i)
        i /= 2
      end

      self
    end

    def pop
      return nil if empty?
      
      # @que has at least two element (e.g. [nil, 1], [nil, 3,2,1])
      swap(@que, 1, @que.size-1)
      ans = @que.pop
      heapify(@que, 1)

      ans
    end

    def top
      empty? ? nil : @que[1]
    end

    def empty?
      size == 0
    end

    def inspect
      "<pq: size=#{size}, top=#{top || "nil"}>"
    end

    private

    def heapify(queue, i)
      
      max_i, left_i, right_i = i, i*2, i*2+1

      if !queue[left_i].nil? and !@cmp.call(queue[max_i], queue[left_i])
        max_i = left_i
      end

      if !queue[right_i].nil? and !@cmp.call(queue[max_i], queue[right_i])
        max_i = right_i
      end

      if max_i != i
        swap(queue, i, max_i)
        heapify(queue, max_i)
      end

    end

    def swap(arr, i1, i2)
      arr[i1], arr[i2] = arr[i2], arr[i1]
    end

  end

  def self.run 

    mf = MedianFinder.new

    mf.add_num(1768)
    mf.find_median()
    mf.add_num(3181)
    mf.find_median()
    mf.add_num(2366)
    mf.find_median()
    mf.add_num(3696)
    mf.find_median()
    mf.add_num(13344)
    mf.find_median()
    mf.add_num(4168)
    mf.find_median()
    mf.add_num(7751)
    mf.find_median()
    mf.add_num(13282)
    mf.find_median()
    mf.add_num(8475)
    mf.find_median()
    mf.add_num(13661)
    mf.find_median()
    mf.add_num(7766)
    mf.find_median()
    mf.add_num(8742)
    mf.find_median()
    mf.add_num(17861)
    mf.find_median()
    mf.add_num(13474)
    mf.find_median()
    mf.add_num(7076)
    mf.find_median()
    mf.add_num(16490)
    mf.find_median()
    mf.add_num(11533)
    mf.find_median()
    mf.add_num(7631)
    mf.find_median()
    mf.add_num(2588)
    mf.find_median()
    mf.add_num(14807)
    mf.find_median()
    mf.add_num(9550)
    mf.find_median()
    mf.add_num(19927)
    mf.find_median()
    mf.add_num(16810)
    mf.find_median()
    mf.add_num(9120)
    mf.find_median()
    mf.add_num(2887)
    mf.find_median()
    mf.add_num(18040)
    mf.find_median()
    mf.add_num(20397)
    mf.find_median()
    mf.add_num(19039)
    mf.find_median()
    mf.add_num(10943)
    mf.find_median()
    mf.add_num(10968)
    mf.find_median()
    mf.add_num(14156)
    mf.find_median()
    mf.add_num(18520)
    mf.find_median()
    mf.add_num(13696)
    mf.find_median()
    mf.add_num(17362)
    mf.find_median()
    mf.add_num(2139)
    mf.find_median()
    mf.add_num(6677)
    mf.find_median()
    mf.add_num(13465)
    mf.find_median()
    mf.add_num(16505)
    mf.find_median()
    mf.add_num(3832)
    mf.find_median()
    mf.add_num(18544)
    mf.find_median()
    mf.add_num(5959)
    mf.find_median()
    mf.add_num(15309)
    mf.find_median()
    mf.add_num(19828)
    mf.find_median()
    mf.add_num(10831)
    mf.find_median()
    mf.add_num(1174)
    mf.find_median()
    mf.add_num(461)
    mf.find_median()
    mf.add_num(10460)
    mf.find_median()
    mf.add_num(18685)
    mf.find_median()
    mf.add_num(20384)
    mf.find_median()
    mf.add_num(16380)
    mf.find_median()
    mf.add_num(11059)
    mf.find_median()
    mf.add_num(2973)
    mf.find_median()
    mf.add_num(11622)
    mf.find_median()
    mf.add_num(8451)
    mf.find_median()
    mf.add_num(16506)
    mf.find_median()
    mf.add_num(188)
    mf.find_median()
    mf.add_num(906)
    mf.find_median()
    mf.add_num(20330)
    mf.find_median()
    mf.add_num(17712)
    mf.find_median()
    mf.add_num(10009)
    mf.find_median()
    mf.add_num(19454)
    mf.find_median()
    mf.add_num(2528)
    mf.find_median()
    mf.add_num(1952)
    mf.find_median()
    mf.add_num(6381)
    mf.find_median()
    mf.add_num(19434)
    mf.find_median()
    mf.add_num(19797)
    mf.find_median()
    mf.add_num(9200)
    mf.find_median()
    mf.add_num(15402)
    mf.find_median()
    mf.add_num(14809)
    mf.find_median()
    mf.add_num(9823)
    mf.find_median()
    mf.add_num(24)
    mf.find_median()
    mf.add_num(7779)
    mf.find_median()
    mf.add_num(6114)
    mf.find_median()
    mf.add_num(4501)
    mf.find_median()
    mf.add_num(17045)
    mf.find_median()
    mf.add_num(11499)
    mf.find_median()
    mf.add_num(12422)
    mf.find_median()
    mf.add_num(277)
    mf.find_median()
    mf.add_num(10142)
    mf.find_median()
    mf.add_num(1754)
    mf.find_median()
    mf.add_num(2621)
    mf.find_median()
    mf.add_num(18990)
    mf.find_median()
    mf.add_num(8577)
    mf.find_median()
    mf.add_num(494)
    mf.find_median()
    mf.add_num(19789)
    mf.find_median()
    mf.add_num(18265)
    mf.find_median()
    mf.add_num(18405)
    mf.find_median()
    mf.add_num(7117)
    mf.find_median()
    mf.add_num(14556)
    mf.find_median()
    mf.add_num(6305)
    mf.find_median()
    mf.add_num(9286)
    mf.find_median()
    mf.add_num(5649)
    mf.find_median()
    mf.add_num(11793)
    mf.find_median()
    mf.add_num(14560)
    mf.find_median()
    mf.add_num(8769)
    mf.find_median()
    mf.add_num(12791)
    mf.find_median()
    mf.add_num(3681)
    mf.find_median()
    mf.add_num(6702)
    mf.find_median()
    mf.add_num(17822)
    mf.find_median()
    mf.add_num(14166)
    mf.find_median()
    mf.add_num(8526)
    mf.find_median()
    mf.add_num(4705)
    mf.find_median()
    mf.add_num(9890)
    mf.find_median()
    mf.add_num(2105)
    mf.find_median()
    mf.add_num(15525)
    mf.find_median()
    mf.add_num(10274)
    mf.find_median()
    mf.add_num(8849)
    mf.find_median()
    mf.add_num(12567)
    mf.find_median()
    mf.add_num(14056)
    mf.find_median()
    mf.add_num(8169)
    mf.find_median()
    mf.add_num(14960)
    mf.find_median()
    mf.add_num(13839)
    mf.find_median()
    mf.add_num(17929)
    mf.find_median()
    mf.add_num(10847)
    mf.find_median()
    mf.add_num(5978)
    mf.find_median()
    mf.add_num(18971)
    mf.find_median()
    mf.add_num(10026)
    mf.find_median()
    mf.add_num(4077)
    mf.find_median()
    mf.add_num(17800)
    mf.find_median()
    mf.add_num(10839)
    mf.find_median()
    mf.add_num(4663)
    mf.find_median()
    mf.add_num(20352)
    mf.find_median()
    mf.add_num(786)
    mf.find_median()
    mf.add_num(15528)
    mf.find_median()
    mf.add_num(11840)
    mf.find_median()
    mf.add_num(15742)
    mf.find_median()
    mf.add_num(382)
    mf.find_median()
    mf.add_num(10234)
    mf.find_median()
    mf.add_num(9663)
    mf.find_median()
    mf.add_num(9045)
    mf.find_median()
    mf.add_num(16650)
    mf.find_median()
    mf.add_num(189)
    mf.find_median()
    mf.add_num(10051)
    mf.find_median()
    mf.add_num(13887)
    mf.find_median()
    mf.add_num(14600)
    mf.find_median()
    mf.add_num(18357)
    mf.find_median()
    mf.add_num(4629)
    mf.find_median()
    mf.add_num(5923)
    mf.find_median()
    mf.add_num(102)
    mf.find_median()
    mf.add_num(16934)
    mf.find_median()
    mf.add_num(11941)
    mf.find_median()
    mf.add_num(4869)
    mf.find_median()
    mf.add_num(20066)
    mf.find_median()
    mf.add_num(708)
    mf.find_median()
    mf.add_num(4104)
    mf.find_median()
    mf.add_num(682)
    mf.find_median()
    mf.add_num(8242)
    mf.find_median()
    mf.add_num(18889)
    mf.find_median()
    mf.add_num(7726)
    mf.find_median()
    mf.add_num(16342)
    mf.find_median()
    mf.add_num(1184)
    mf.find_median()
    mf.add_num(16599)
    mf.find_median()
    mf.add_num(6129)
    mf.find_median()
    mf.add_num(839)
    mf.find_median()
    mf.add_num(7179)
    mf.find_median()
    mf.add_num(13523)
    mf.find_median()
    mf.add_num(6333)
    mf.find_median()
    mf.add_num(6333)
    mf.find_median()
    mf.add_num(8176)
    mf.find_median()
    mf.add_num(7605)
    mf.find_median()
    mf.add_num(219)
    mf.find_median()
    mf.add_num(14372)
    mf.find_median()
    mf.add_num(5557)
    mf.find_median()
    mf.add_num(12689)
    mf.find_median()
    mf.add_num(10839)
    mf.find_median()
    mf.add_num(1550)
    mf.find_median()
    mf.add_num(18342)
    mf.find_median()
    mf.add_num(16379)
    mf.find_median()
    mf.add_num(13003)
    mf.find_median()
    mf.add_num(5824)
    mf.find_median()
    mf.add_num(16187)
    mf.find_median()
    mf.add_num(685)
    mf.find_median()
    mf.add_num(11109)
    mf.find_median()
    mf.add_num(20345)
    mf.find_median()
    mf.add_num(7322)
    mf.find_median()
    mf.add_num(17437)
    mf.find_median()
    mf.add_num(11362)
    mf.find_median()
    mf.add_num(11348)
    mf.find_median()
    mf.add_num(9064)
    mf.find_median()
    mf.add_num(4978)
    mf.find_median()
    mf.add_num(5490)
    mf.find_median()
    mf.add_num(404)
    mf.find_median()
    mf.add_num(17862)
    mf.find_median()
    mf.add_num(7997)
    mf.find_median()
    mf.add_num(16300)
    mf.find_median()
    mf.add_num(6447)
    mf.find_median()
    mf.add_num(14819)
    mf.find_median()
    mf.add_num(2648)
    mf.find_median()
    mf.add_num(11108)
    mf.find_median()
    mf.add_num(18522)
    mf.find_median()
    mf.add_num(10501)
    mf.find_median()
    mf.add_num(11689)
    mf.find_median()
    mf.add_num(12426)
    mf.find_median()
    mf.add_num(4122)
    mf.find_median()
    mf.add_num(6393)
    mf.find_median()
    mf.add_num(18208)
    mf.find_median()
    mf.add_num(19882)
    mf.find_median()
    mf.add_num(9438)
    mf.find_median()
    mf.add_num(7176)
    mf.find_median()
    mf.add_num(19867)
    mf.find_median()
    mf.add_num(5008)
    mf.find_median()
    mf.add_num(7377)
    mf.find_median()
    mf.add_num(193)
    mf.find_median()
    mf.add_num(10418)
    mf.find_median()
    mf.add_num(19021)
    mf.find_median()
    mf.add_num(16368)
    mf.find_median()
    mf.add_num(9135)
    mf.find_median()
    mf.add_num(19201)
    mf.find_median()
    mf.add_num(17383)
    mf.find_median()
    mf.add_num(5967)
    mf.find_median()
    mf.add_num(14254)
    mf.find_median()
    mf.add_num(3846)
    mf.find_median()
    mf.add_num(12680)
    mf.find_median()
    mf.add_num(9908)
    mf.find_median()
    mf.add_num(4089)
    mf.find_median()
    mf.add_num(8658)
    mf.find_median()
    mf.add_num(9076)
    mf.find_median()
    mf.add_num(9478)
    mf.find_median()
    mf.add_num(8263)
    mf.find_median()
    mf.add_num(4512)
    mf.find_median()
    mf.add_num(14221)
    mf.find_median()
    mf.add_num(6296)
    mf.find_median()
    mf.add_num(2444)
    mf.find_median()
    mf.add_num(11765)
    mf.find_median()
    mf.add_num(8587)
    mf.find_median()
    mf.add_num(3066)
    mf.find_median()
    mf.add_num(5716)
    mf.find_median()
    mf.add_num(18840)
    mf.find_median()
    mf.add_num(9965)
    mf.find_median()
    mf.add_num(12035)
    mf.find_median()
    mf.add_num(8946)
    mf.find_median()
    mf.add_num(12118)
    mf.find_median()
    mf.add_num(11603)
    mf.find_median()
    mf.add_num(5458)
    mf.find_median()
    mf.add_num(9077)
    mf.find_median()
    mf.add_num(19132)
    mf.find_median()
    mf.add_num(8213)
    mf.find_median()
    mf.add_num(4324)
    mf.find_median()
    mf.add_num(1228)
    mf.find_median()
    mf.add_num(17439)
    mf.find_median()
    mf.add_num(18123)
    mf.find_median()
    mf.add_num(6459)
    mf.find_median()
    mf.add_num(15910)
    mf.find_median()
    mf.add_num(10669)
    mf.find_median()
    mf.add_num(1086)
    mf.find_median()
    mf.add_num(9400)
    mf.find_median()
    mf.add_num(18870)
    mf.find_median()
    mf.add_num(9929)
    mf.find_median()
    mf.add_num(9990)
    mf.find_median()
    mf.add_num(17760)
    mf.find_median()
    mf.add_num(5868)
    mf.find_median()
    mf.add_num(13765)
    mf.find_median()
    mf.add_num(2462)
    mf.find_median()
    mf.add_num(6446)
    mf.find_median()
    mf.add_num(19590)
    mf.find_median()
    mf.add_num(8938)
    mf.find_median()
    mf.add_num(11355)
    mf.find_median()
    mf.add_num(10679)
    mf.find_median()
    mf.add_num(4818)
    mf.find_median()
    mf.add_num(16978)
    mf.find_median()
    mf.add_num(243)
    mf.find_median()
    mf.add_num(11693)
    mf.find_median()
    mf.add_num(10295)
    mf.find_median()
    mf.add_num(13403)
    mf.find_median()
    mf.add_num(5126)
    mf.find_median()
    mf.add_num(4772)
    mf.find_median()
    mf.add_num(5351)
    mf.find_median()
    mf.add_num(789)
    mf.find_median()
    mf.add_num(19759)
    mf.find_median()
    mf.add_num(5342)
    mf.find_median()
    mf.add_num(10674)
    mf.find_median()
    mf.add_num(17287)
    mf.find_median()
    mf.add_num(20180)
    mf.find_median()
    mf.add_num(14940)
    mf.find_median()
    mf.add_num(18630)
    mf.find_median()
    mf.add_num(14467)
    mf.find_median()
    mf.add_num(18404)
    mf.find_median()
    mf.add_num(18556)
    mf.find_median()
    mf.add_num(11644)
    mf.find_median()
    mf.add_num(2946)
    mf.find_median()
    mf.add_num(7620)
    mf.find_median()
    mf.add_num(19467)
    mf.find_median()
    mf.add_num(18391)
    mf.find_median()
    mf.add_num(16486)
    mf.find_median()
    mf.add_num(16291)
    mf.find_median()
    mf.add_num(1096)
    mf.find_median()
    mf.add_num(12200)
    mf.find_median()
    mf.add_num(5641)
    mf.find_median()
    mf.add_num(13434)
    mf.find_median()
    mf.add_num(9436)
    mf.find_median()
    mf.add_num(14408)
    mf.find_median()
    mf.add_num(10710)
    mf.find_median()
    mf.add_num(5120)
    mf.find_median()
    mf.add_num(5954)
    mf.find_median()
    mf.add_num(16400)
    mf.find_median()
    mf.add_num(11221)
    mf.find_median()
    mf.add_num(4706)
    mf.find_median()
    mf.add_num(15090)
    mf.find_median()
    mf.add_num(4940)
    mf.find_median()
    mf.add_num(16426)
    mf.find_median()
    mf.add_num(16991)
    mf.find_median()
    mf.add_num(9972)
    mf.find_median()
    mf.add_num(19559)
    mf.find_median()
    mf.add_num(9092)
    mf.find_median()
    mf.add_num(12857)
    mf.find_median()
    mf.add_num(15527)
    mf.find_median()
    mf.add_num(11514)
    mf.find_median()
    mf.add_num(19781)
    mf.find_median()
    mf.add_num(17590)
    mf.find_median()
    mf.add_num(6694)
    mf.find_median()
    mf.add_num(6736)
    mf.find_median()
    mf.add_num(5624)
    mf.find_median()
    mf.add_num(10589)
    mf.find_median()
    mf.add_num(20320)
    mf.find_median()
    mf.add_num(6487)
    mf.find_median()
    mf.add_num(19074)
    mf.find_median()
    mf.add_num(10132)
    mf.find_median()
    mf.add_num(20427)
    mf.find_median()
    mf.add_num(465)
    mf.find_median()
    mf.add_num(11186)
    mf.find_median()
    mf.add_num(19120)
    mf.find_median()
    mf.add_num(5081)
    mf.find_median()
    mf.add_num(6648)
    mf.find_median()
    mf.add_num(9294)
    mf.find_median()
    mf.add_num(14751)
    mf.find_median()
    mf.add_num(13117)
    mf.find_median()
    mf.add_num(8846)
    mf.find_median()
    mf.add_num(18994)
    mf.find_median()
    mf.add_num(17383)
    mf.find_median()
    mf.add_num(9983)
    mf.find_median()
    mf.add_num(696)
    mf.find_median()
    mf.add_num(1730)
    mf.find_median()
    mf.add_num(19670)
    mf.find_median()
    mf.add_num(17930)
    mf.find_median()
    mf.add_num(17244)
    mf.find_median()
    mf.add_num(13957)
    mf.find_median()
    mf.add_num(2002)
    mf.find_median()
    mf.add_num(3160)
    mf.find_median()
    mf.add_num(4001)
    mf.find_median()
    mf.add_num(2012)
    mf.find_median()
    mf.add_num(6664)
    mf.find_median()
    mf.add_num(2574)
    mf.find_median()
    mf.add_num(14480)
    mf.find_median()
    mf.add_num(13773)
    mf.find_median()
    mf.add_num(11745)
    mf.find_median()
    mf.add_num(14477)
    mf.find_median()
    mf.add_num(6537)
    mf.find_median()
    mf.add_num(15390)
    mf.find_median()
    mf.add_num(17494)
    mf.find_median()
    mf.add_num(13766)
    mf.find_median()
    mf.add_num(13141)
    mf.find_median()
    mf.add_num(20013)
    mf.find_median()
    mf.add_num(8059)
    mf.find_median()
    mf.add_num(3207)
    mf.find_median()
    mf.add_num(17012)
    mf.find_median()
    mf.add_num(6631)
    mf.find_median()
    mf.add_num(4004)
    mf.find_median()
    mf.add_num(12523)
    mf.find_median()
    mf.add_num(20130)
    mf.find_median()
    mf.add_num(5202)
    mf.find_median()
    mf.add_num(4307)
    mf.find_median()
    mf.add_num(10746)
    mf.find_median()
    mf.add_num(4028)
    mf.find_median()
    mf.add_num(16231)
    mf.find_median()
    mf.add_num(11236)
    mf.find_median()
    mf.add_num(13017)
    mf.find_median()
    mf.add_num(15323)
    mf.find_median()
    mf.add_num(7958)
    mf.find_median()
    mf.add_num(9042)
    mf.find_median()
    mf.add_num(6907)
    mf.find_median()
    mf.add_num(6011)
    mf.find_median()
    mf.add_num(97)
    mf.find_median()
    mf.add_num(4403)
    mf.find_median()
    mf.add_num(17352)
    mf.find_median()
    mf.add_num(18833)
    mf.find_median()
    mf.add_num(63)
    mf.find_median()
    mf.add_num(7214)
    mf.find_median()
    mf.add_num(17582)
    mf.find_median()
  end
end

Benchmark.bm(10) do |x|
  x.report('version1') { Version1::run;sleep(5) }
  x.report('version2') { Version2::run }
end
